language: node_js

node_js:
  - "node"

cache:
  directories:
    - "tests/dependencies/kinetic-java"

script:
  - npm run --silent lint
  - npm run --silent test
  - npm run --silent tests_functional
